schema_version: 1

context:
  name: types-aiobotocore
  version: 2.15.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_aiobotocore-${{ version }}.tar.gz
  sha256: 63e6a456ccc33e2ca350aae588cfdbbb94bdecf3533e6a8578f736c5b2b85607

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - botocore-stubs
    - typing-extensions >=4.1.0

tests:
  - package_contents:
      site_packages:
        - aiobotocore-stubs/__init__.pyi

about:
  summary: Type annotations for aiobotocore
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/youtype/mypy_boto3_builder
  repository: https://github.com/youtype/mypy_boto3_builder

extra:
  recipe-maintainers:
    - peterbygrave
    - xhochy
