schema_version: 1

context:
  name: types-aiobotocore
  version: "3.2.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_aiobotocore-${{ version }}.tar.gz
  sha256: 79199e9cb564352dc9ef987fa1bff753a3757fdc1cc5439ab421e6db5ee90ea6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - botocore-stubs
    - typing-extensions >=4.1.0

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
  - package_contents:
      site_packages:
        - aiobotocore-stubs/__init__.pyi

about:
  summary: Type annotations for aiobotocore
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/youtype/mypy_boto3_builder
  repository: https://github.com/youtype/mypy_boto3_builder

extra:
  recipe-maintainers:
    - peterbygrave
    - xhochy
