schema_version: 1

context:
  name: types-aiobotocore
  version: "2.26.0.post1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/types_aiobotocore-${{ version }}.tar.gz
  sha256: a0aadb9dfd10ecb2bca4b2eac59c71a7536b50145f3027aebf80084589252ed4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - botocore-stubs
    - typing-extensions >=4.1.0

tests:
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check
  - package_contents:
      site_packages:
        - aiobotocore-stubs/__init__.pyi

about:
  summary: Type annotations for aiobotocore
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/youtype/mypy_boto3_builder
  repository: https://github.com/youtype/mypy_boto3_builder

extra:
  recipe-maintainers:
    - peterbygrave
    - xhochy
